[package]
name = "imavafe/rorooms"
description = "An all-in-one social framework for Roblox"
version = "0.1.0-dev"
license = "MIT"
authors = ["Avafe"]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Knit = "sleitnick/knit@^1.4.7"
Component = "sleitnick/component@^2.4.6"
Loader = "sleitnick/loader@^2.0.0"
RemoteComponent = "encodedvenom/remotecomponent@^1.0.2"
Trove = "sleitnick/trove@1.2.0"
Signal = "sleitnick/signal@2.0.1"
NeoHotbar = "imavafe/neohotbar@1.1.1"
BloxstrapRPC = "pizzaboxer/bloxstrap-rpc-sdk@1.0.1"
t = "osyrisrblx/t@3.1.1"
OnyxUI = "imavafe/onyx-ui@0.2.3"
Future = "red-blox/future@1.0.1"
RateLimit = "red-blox/ratelimit@1.0.1"
Fetch = "red-blox/fetch@2.0.0"
