[dependencies]
BloxstrapRPC = "pizzaboxer/bloxstrap-rpc-sdk@^1.0.1"
ColorUtils = "csqrl/colour-utils@^1.4.1"
Component = "sleitnick/component@^2.4.6"
Fetch = "red-blox/fetch@^2.0.0"
Fusion = "elttob/fusion@^0.3.0"
Future = "red-blox/future@^1.0.1"
Knit = "sleitnick/knit@^1.4.7"
Loader = "sleitnick/loader@^2.0.0"
NeoHotbar = "imavafe/neohotbar@^1.1.1"
OnyxUI = "imavafe/onyx-ui@^0.5.0"
ProfileService = "grilme99/profileservice@^1.0.0"
RateLimit = "red-blox/ratelimit@^1.0.1"
RemoteComponent = "encodedvenom/remotecomponent@^1.0.2"
Signal = "sleitnick/signal@^2.0.1"
Trove = "sleitnick/trove@^1.2.0"
Zone = "imavafe/zoneplus-reupload@^3.2.0"
t = "osyrisrblx/t@^3.1.1"

[package]
authors = ["Avafe"]
license = "MIT"
name = "imavafe/rorooms"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "0.6.2"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]
